### ISSUE TITLE
Update dockerfile-maven to 1.4.9

### ISSUE THREAD

**Issue by artem-v** [scalecube/scalecube-parent#39]
We are on 1.4.4, let's update onto [1.4.9](https://github.com/spotify/dockerfile-maven/releases/tag/v1.4.9)

**Comment by dmytro-lazebnyi** [comment]
`dockerfile-maven-plugin` breaks `install` phase on maven `3.3.x` version.

**Comment by dmytro-lazebnyi** [comment]
@artem-v 
`dockerfile-maven-plugin` breaks `install` phase on maven `3.3.x` version.
