### ISSUE TITLE
Enhance corporate pom structure

### ISSUE THREAD

**Issue by dmytro-lazebnyi** [scalecube/scalecube-parent#6]
### Motivation
Corporate POM have to declare all third-party plugins **and dependepcies**.
All project have to use **same** versions of any **third-party** library to avoid difference of dependencies.

### Needs to be done
* Plugins have to be described in `pluginManagement` section and simply used in `plugins` section
* Dependencies have to be described `dependencyManagement` sections
* Versions of dependencies have to be declared in `properties` section as it is done for plugins

**Comment by aharonha** [comment]
@dmytro-lazebnyi As I see it, dependencies are to be set in a `bom` rather then `pom`
So, for example we would have a pom package for depending on multiple artifacts, then on the parent pom (not the super) we can add a *dependency* with scope `import` to this `bom` that would import all of our dependencies.
@scalecube/developers What do you think?

**Comment by aharonha** [comment]
Lets agree on some guidelines:

1. we should have ~~all of our~~ ++ *only* ++ the most common third party dependencies in the super pom
2. test scope should also be set.
3. sibling projects (modules in the same git repository) are not to be managed
4. let's have a discussion about scalecube projects which are not in the same repository
5. let's discuss https://github.com/scalecube/enable-ci-cd-using-travis/issues/17

**Comment by ronenhamias** [comment]
1. we should have all of our ++ _only_ ++ the most common third party dependencies in the super pom

having a lib version in this project makes it really hard to update and test.
i really suggest to keep only administrative stuff here that are rock solid relate to build and release and general project standards.

**Comment by dmytro-lazebnyi** [comment]
@ronenhamias 
Yep, looks like it was a **not good idea** to have **any** common dependencies in **corporate** pom.
I've just created pull request #55 to remove even `test` dependencies.
