### ISSUE TITLE
Reduce amount of log output generated by some plugins

### ISSUE THREAD

**Issue by artem-v** [scalecube/scalecube-parent#69]
Subj.

[log.txt](https://github.com/scalecube/scalecube-parent/files/3778009/log.txt)

**Comment by artem-v** [comment]
Candidates for removal:
`maven-javadoc-plugin:2.10.4:jar (attach-javadocs)`
Candidates for mute:
`maven-dependency-plugin:3.1.0:copy-dependencies`
`maven-install-plugin:2.4:install, nexus-staging-maven-plugin:1.6.8:deploy` ?? don't know though is this good idea to mute it.

**Comment by aharonha** [comment]
https://github.com/scalecube/scalecube-travis-ci/pull/35

**Comment by aharonha** [comment]
@artem-v  We should also release this project and bump version of it on all projects in scalecube
